name: Build

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    Build:
      needs: []
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [windows-2022, windows-2025]
          configuration: [Debug, Release]
          platform: [x86, x64, ARM64]
      steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce
        with:
          msbuild-architecture: x64
      - name: Nuget Restore
        run: nuget.exe restore templates/templates.sln
      - name: Build
        run: msbuild templates/templates.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
    Complete:
      name: Complete
      if: always()
      needs: Build
      runs-on: ubuntu-latest
      permissions: {}
      steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe
        with:
          jobs: ${{ toJSON(needs) }}
